### ISSUE TITLE
Add details about meetups

### ISSUE THREAD

**Issue by jangondol** [pyconsk/pycon.sk#10]
Some things keep popping up: **how long do the meetups take**? (Approximately one hour plus one hour discussion.) Also: **admission is free** of charge. Also: there is no parking around but there are good public transportation options. Also: the language is Slovak but we're **happy to welcome hackers from abroad** (we can summarize the main points of the talk every couple of minutes). Etc.

Perhaps we could add this to https://pycon.sk/sk/meetup.html

**Comment by ricco386** [comment]
@jangondol sound good, can you get some text together (ideal in Slovak and English), that we can update on  https://pycon.sk/sk/meetup.html

**Comment by jangondol** [comment]
**Vstup na meetupy je bezplatný**. Približný čas trvania meetupov: dve hodiny (cca hodina prezentácia, hodina alebo viac diskusia). Miesto konania: ProgressBar hackerspace, Michalská 3 (centrum Bratislavy). Neďaleké zastávky MHD: [Zochova](https://imhd.sk/ba/cestovny-poriadok/zastavka/3723/Zochova), [Kapucínska](https://imhd.sk/ba/cestovny-poriadok/zastavka/1067/Kapucinska), neďaleké platené parkovanie: [Uršulínska](http://www.ppg.sk/), [Hotel Carlton](http://www.carlton.sk/), [Hotel Park Inn](http://www.parkinn.com/hotel-bratislava).

**Admission is free of charge**. Approximate duration: two hours (one hour presentation, one hour or more: discussion). Location: ProgressBar hackerspace, Michalská 3 (center of Bratislava). Nearby public transportation stops: Zochova, Kapucínska, nearby paid parking: Uršulínska, Hotel Carlton, Hotel Park Inn.

(EN links same as SK version)
