### ISSUE TITLE
Meetups: add links to GitHub

### ISSUE THREAD

**Issue by jangondol** [pyconsk/pycon.sk#12]
The [Meetup page](https://pycon.sk/sk/meetup.html) should point to the [GitHub repo](https://github.com/pyconsk/meetup). Otherwise some people will never know that such a repo exists.

Perhaps we could also link directly to the individual folders within the repo from the individual meetup pages (e.g. [Meetup 1 on PyCon page](https://pycon.sk/en/ba-01-meetup.html) points to [Meetup 1 on GitHub](https://github.com/pyconsk/meetup/tree/master/Bratislava/201507) -- would be nice and easy to find materials). Any volunteers? :-)

**Comment by mnalevanko** [comment]
Thanks a lot! Didn't know the meetup had its own repo.

mn

**Comment by mbag** [comment]
I'll take it, if there are no other takers :) 
Would it be sufficient to put on [Meetup page](https://pycon.sk/sk/meetup.html) above individual meetups line like this:
Github Meetup repo: [https://github.com/pyconsk/meetup](https://github.com/pyconsk/meetup)

And on individual meetup pages similar line to individual neetup repo, that would be located above line 
Contact:

I'll create branch for this feature, then rebase it into master as single commit (in case there are multiple).

**Comment by jangondol** [comment]
@mbag Thanks! :) If you want, consider adding a GitHub icon or some other way to highlight this, so it's more visible and not overlooked. Your call.

**Comment by ricco386** [comment]
@mbag yes I think it would be enought, possibly look at bootstrap icons if there is github icon, if not text with link is fine I guess...

**Comment by mbag** [comment]
Added new branch add_meetup_links. Please try running it, to see if this style is acceptable. 
If it's OK, please don't merge this branch :) I would like to rebase it, so that we have straight commit history. Furthermore I haven't done a rebase in a while :)
