### ISSUE TITLE
Add link to Python docs + learning resources near the console

### ISSUE THREAD

**Issue by jangondol** [pyconsk/pycon.sk#14]
At the [Python console](https://pycon.sk/sk/console.html) we could perhaps point to some **"learn Python" resources** or code examples? Some ideas: Dive into Python ([in Czech](https://web.archive.org/web/20111116104317/http://knihy.nic.cz/files/nic/edice/mark_pilgrim_dip3_ver3.pdf)), "Learn Python" ([Android app](https://play.google.com/store/apps/details?id=com.sololearn.python)),...

Why this could be a good idea -- there are two kinds of people: 1) those sho already know Python (they are not the primary audience of the online console) and 2) those who haven't tried Python yet (they will *not know* what to type into the console and **perhaps they could use some help** -- either a few code examples or a pointer to docs / tutorial).

Once we have more resources to "learn Python", we can turn it into a **stand-alone "learn Python" page** / section of the website.

**Comment by mnalevanko** [comment]
Just for the sake of curiosity: are these resources supposed to be in
Slovak/Czech or in any language?

I've gone through many sites in the past few years, found several
high-quality resources.

B/w it doesn't make much sense to me to create a new stand-alone section of
the PyCon website. I view the site as a special purpose web project.
Perhaps we could think of creating a brand new website for all wannabe
coders. Have your say.

mn

**Comment by jangondol** [comment]
I think that most people will understand enough English to read technical texts. But there are some for whom this may not be the case or who prefer Slovak / Czech (children, older people), so it may be useful to have some local resources as well.

Let's start with something small and if it ever grows into something bigger, we can discuss whether we'll spin it off as a separate website section or a stand-alone project. Deciding now feels like premature optimization... :-)

**Comment by mbag** [comment]
As it was mentioned, there are many learning resources on the web and IMHO we shouldn't try to compete with them, rather we should point to them.

The interpreter that is embedded into webpage is not a real Python console, rather it's there to show how simple Python syntax is and to tease imagination of the newbies :)

My idea was to have some simple code examples that people can try in Brython and then give them info how to install python and start coding on their own machine. Naturally, we would point them to tutorials. We would also put email address where they could send us questions or problems with getting started, so we can have FAQ.

I'm also not opposed to creating dedicated web page for python learners. However, my opinion is that we should first find demographic on which we will focus. For example, SPy wants to focus on children and Daniel and Richard have some experience with teaching kids to code, maybe we could orfanize some coding sessions on the weekends and based on this experience create learners' webpage. 

But that would be rather complicated thing to do now :)we should first cincentrate on conference. 

In the meantime I'll revive the console branvh and cimmit some resources as mentioned in posts above. So we can get tgat out asap.

**Comment by jangondol** [comment]
> there are many learning resources on the web and IMHO we shouldn't try to compete with them, rather we should point to them.

Yes, that is the very first sentence of this issue... :-)

We have the console, let's help people *do something* with it. Let's do something super simple and develop it more later (if needed).

**Comment by ricco386** [comment]
I have been in touch with guy who has registered python.sk which would be ideal for such materials. He told me he will give it to us under promise it wont be used for commercial purposes, which is fine by us.

In my opinion pycon.sk should be for conference and meetups, rest (materials, forums, anything else) should be on python.sk, how do we do it is matter we should focus on after PyCon.
