### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by jangondol** [pyconsk/pycon.sk#6]
It might be useful to create a FAQ document. Some possible items to include:

- I would like to help you as a volunteer. What can I do? -- Thank you, we appreciate it! Please get in touch with us at info@pycon.sk
- I'm a teacher and would like to take my students to your event. Are group discounts available? -- Yes, as long as we can accommodate the group. Please contact us and let us discuss the specifics. (Why is this not handled automatically? Because a lot depends on how many spaces in the room we have left, how close the conference date is, etc..)
- My 13-year-old son would like to attend the conference but someone has to go with him. Do we need to purchase two tickets? -- No. While we welcome your support if you decide to buy two tickets, you only need to buy a discounted (student) ticket for your son. HOWEVER, please let us know the name of the guardian (i.e., you or somebody else), so we can issue a free ticket, which will be needed to enter the premises.

(This is just something to start with. We can add other questions as they arrive, maybe we could re-visit the e-mails sent to us...)

**Comment by jangondol** [comment]
Actually, it may be better to add the questions about tickets to https://pycon.sk/en/tickets.html (instead of creating a stand-alone FAQ document) -- easier to find them there. Interestingly, answers to the questions are already provided on this page but people still keep asking them...

**Comment by dn0** [comment]
Closing this in the light of recent events (https://twitter.com/pyconsk/status/690576572735164420)
