### ISSUE TITLE
Automatic publishing of pycon.sk

### ISSUE THREAD

**Issue by jangondol** [pyconsk/pycon.sk#7]
So @ricco386 did a nice job describing how to build the website locally in the README. I wonder if there's a way to make this process automatic?

It would be very cool if we could make quick edits / additions to the site and have some mechanism of automatic online publishing (perhaps through some CI system?). My theory is that making the whole process even easier could encourage community contributions. For example, from time to time I see something on the site that should be fixed / added and instead of taking care of it right away I just fire off an e-mail to others or completely forget about it.

Perhaps it's just me (and yes, I have push access to the repo) but perhaps this would be also welcome by others? In case we want to be extra careful about deployments, we could deploy to the internal staging server or have separate branches for staging and master.

Any thoughts? Happy to discuss this, either here or off-line when we meet... :-)

**Comment by ricco386** [comment]
Thanks, sounds interesting but I dont know how to do it without giving more thought into this... I am not saying no, but unfortunately it is low priority at this point with this workload... If you have some solution, that we just take and use that would be great and we can give it a try and see how it works.

**Comment by ricco386** [comment]
Dano made a core server where anyone can ssh, so whoever would like to have access to our network can send me or dano his public key in a secure way :) and we will add that person to authorized and can update web/mails/private stuff any time... Unfortunately due to workload I probably wont do the Ludolph experiment.

**Comment by jangondol** [comment]
Is there any way to automate the builds, e.g. like @mirobeka showed us yesterday at the meetup? That would make things really easy.

Intended workflow: push change -> build to test environment happens automatically (no ssh or anything).

**Comment by ricco386** [comment]
I would be more than happy if anyone does that... If we find a volunteer who wants to play with the servers he can get a root privileges, currently all the admin work on servers is done by @dn0 so if the volunteer will contact him they can discuss his/her ideas.

**Comment by xen0l** [comment]
I’ll take care of this. I’ll setup internal jenkins instance on a zone.

ETA: end of week/beginning of the next one

Can you come up with some conditiions, which need to be met in order for the PR to be deployed into the staging?

Adam

**Comment by mbag** [comment]
I could write some basic tests over the weekend. For example test flask app if existing webpages return 200OK or some other types of sanity checks.
@xen0l Did you have something else in mind?

**Comment by xen0l** [comment]
I had something like spellchecker runs in mind.

Adam

**Comment by jangondol** [comment]
For deployment to staging, let's have some basic tests to make sure the site won't break. While spell checker may be useful, it could be hard to automate (e.g. speaker names may throw off an exception).

Deployment to production is more tricky: should we have separate branches for development (which deploys to the staging server) and for production (which deploys to the live server)? Should we perhaps tag "releases" (once we decide the content looks good, we tag it with %datetime%) and every tagged release gets deployed to production? Or do you have other ideas what to release?

Feedback welcome.

**Comment by dn0** [comment]
Why don't we just push directly to the staging server?

**Comment by jangondol** [comment]
@dn0 Exactly:

1) On GitHub push: run tests & if passed -> push to staging.
2) When a condition is met (e.g. release is tagged by one of the people on the team, button is clicked after manually checking content) -> run tests & if passed -> push to production.

For me, the questions what condition should be met. Tagging the release seems like the easiest. Or we could do separate branches. Or something else entirely. Ideas?
